### ISSUE TITLE
setup ros2 keyでSSLのエラーが出る

### ISSUE THREAD

**Issue by TatsukiNishimura** [OUXT-Polaris/ouxt_automation#192]
```
sh setup.sh
```
を実行してros2のインストールをする際、
setup ros2 keyのタスクで
```
Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
```
のエラーが出てしまう。

環境
* Ubuntu 20.04 LTS
* ROS galactic

**Comment by TatsukiNishimura** [comment]
https://github.com/OUXT-Polaris/ouxt_automation/blob/c63b60ffd201c3df26dfb426c9126af02571401b/ansible/roles/ros2/tasks/main.yml#L31
に
```
name: setup ros2 keys
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
  environment:
    SSL_CERT_FILE: (証明書のパス)
```
を書き加えるとエラーがなくなった。
ただ、このパスは人によって異なるからどうすればいいんだろう…
